name: milala-management

on:
  push:
    branches: [ "main" ]

jobs:
  milala-management:

    runs-on: ubuntu-latest

    steps:
    - name: "Update Codebase"
      uses: appleboy/ssh-action@master
      with:
          host: "103.171.85.97"
          username: "root"
          # Hapus baris 'password'
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Gunakan secret untuk kunci privat
          port: 22
          script: |
            cd /var/www/milala-management
            git pull origin main
            git status
